### ISSUE TITLE
[Bug] browser validation does not report errors.

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#42] opened 2023-05-12 14:07 UTC
In previous version you would get something like this from invalid email address:

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/7188159/5ba6b4a7-15e5-4e4e-b0b7-224783d04d7a)

Now it "identifies" the error and prevents the submission, but does not display the message or give any hint that's failing.

**Comment by promatik** [comment] 2023-07-10 01:31
@pxpm I tried this one, and it's working as expected;
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/1838187/19cbdc68-a35f-4a8d-809b-b37697b629aa)

Since this is 2 months old now, this was probably fixed in the between, if it's not, please reopen and let me know how to reproduce 👌

**Closed by promatik** 2023-07-10 01:31 UTC
